### ISSUE TITLE
Use MKL for math

### ISSUE THREAD

**Issue by jrussell25** [jrussell25/CS205-ADMM#2]
There may be several ways of doing this and I'm not sure which is best. [This is probably a good place to start](https://xtensor-blas.readthedocs.io/en/latest/performance.html) but I admit I've been confused about how to call to blas from xtensor.

For the lasso example it would certainly be worth using blas to be able to cholesky solve like boyd does. Other examples may have other needs.

**Comment by liyiliang13** [comment]
MKL is running successfully on Cannon
